// js/state.js
export const state = {
    currentUser: null,
    allAgents: [],
    allWEngines: [],
    allDiscs: [],
    mainStatsGrowth: [],
    subStatsGrowth: [],
    rankingData: {},
    myCharacters: [],
    myBuilds: [],
    myWEngines: [],
    myDiscs: [],
    comparisonList: [],
    chatHistories: { general: [], disc: [], character: [], party: [] },
    activeFilters: {},
    roleChart: null,
    attributeChart: null,
    consentGiven: false,
    aiModel: 'flash',
};
